export const b2cProducts = [
    {
        id: "b2c-01",
        name: "Roasted Foxnuts (Makhana) – Classic",
        description: "Light, crunchy snack with clean ingredient labeling and export-ready packaging.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-02",
        name: "Roasted Foxnuts (Makhana) – Himalayan Pink Salt",
        description: "Balanced seasoning and consistent roast profile, designed for repeat purchase.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-03",
        name: "Roasted Foxnuts (Makhana) – Peri Peri",
        description: "Bold flavor option with clear allergen notes and batch-coded traceability.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-04",
        name: "Premium Foxnuts (Makhana) – Unsalted",
        description: "Minimal ingredients, ideal for health-conscious customers and family snacking.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-05",
        name: "Spice Blend – Everyday Masala",
        description: "Kitchen staple blend with consistent aroma profile and moisture-controlled packing.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-06",
        name: "Spice Blend – Grilling & Marinade",
        description: "Built for quick marinades and roasting; suitable for home cooks and gifting.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-07",
        name: "Tea & Infusion – Ginger Lemon",
        description: "Comfort-forward infusion with premium ingredient selection and clear usage notes.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-08",
        name: "Tea & Infusion – Tulsi Blend",
        description: "Traditional wellness blend with export-ready labeling and stable shelf presentation.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-09",
        name: "Hand-crafted Leather Tote – Minimal",
        description: "Structured silhouette with strong stitching standards and premium finishing.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-10",
        name: "Hand-crafted Leather Crossbody",
        description: "Everyday carry with durable hardware selection and consistent craftsmanship.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-11",
        name: "Leather Wallet – Classic",
        description: "Practical compartments and clean edge finishing for a premium customer experience.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-12",
        name: "Leather Passport Holder",
        description: "Travel-ready accessory with reinforced seams and minimal, professional styling.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-13",
        name: "Home Utility Organizer",
        description: "Clean, durable build with a catalog-friendly design and practical use cases.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-14",
        name: "Kitchen Storage Set",
        description: "Simple, high-utility packaging designed for clarity on marketplace listings.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-15",
        name: "Gift-ready Assorted Snack Pack",
        description: "Curated flavors for gifting and sampling, optimized for strong unboxing impressions.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
    {
        id: "b2c-16",
        name: "Everyday Essentials Bundle",
        description: "Multi-item bundle concept built to improve value perception and marketplace conversion.",
        imageSrc: "/placeholder-product.svg",
        amazonHref: "https://www.amazon.com",
    },
];
